/* Auto-generated by create_boost_header.py for file /home/johannes/nasa/rdt-toolchain-2.9/install/share/kdl_msgs/cmake/../msg/JntArray.msg */
#ifndef KDL_MSGS_BOOST_SERIALIZATION_JNTARRAY_H
#define KDL_MSGS_BOOST_SERIALIZATION_JNTARRAY_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <kdl_msgs/JntArray.h>
#include <kdl_typekit/typekit/Types.hpp>

#endif // KDL_MSGS_BOOST_SERIALIZATION_JNTARRAY_H

