/* Auto-generated by create_boost_header.py for file /home/johannes/nasa/rdt-toolchain-2.9/install/share/kdl_msgs/cmake/../msg/Rotation.msg */
#ifndef KDL_MSGS_BOOST_SERIALIZATION_ROTATION_H
#define KDL_MSGS_BOOST_SERIALIZATION_ROTATION_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <kdl_msgs/Rotation.h>
#include <kdl_typekit/typekit/Types.hpp>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::kdl_msgs::Rotation_<ContainerAllocator>  & m, unsigned int version)
{
    serialize(a, static_cast< ::KDL::Rotation &>(m), version);
}

} // namespace serialization
} // namespace boost

#endif // KDL_MSGS_BOOST_SERIALIZATION_ROTATION_H

